# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IOESDemo.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IOESDemo(object):
    def setupUi(self, IOESDemo):
        IOESDemo.setObjectName("IOESDemo")
        IOESDemo.resize(1424, 917)
        self.centralwidget = QtWidgets.QWidget(IOESDemo)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.edtURL = QtWidgets.QLineEdit(self.centralwidget)
        self.edtURL.setObjectName("edtURL")
        self.verticalLayout.addWidget(self.edtURL)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edtImagePath = QtWidgets.QLineEdit(self.centralwidget)
        self.edtImagePath.setText("")
        self.edtImagePath.setReadOnly(True)
        self.edtImagePath.setObjectName("edtImagePath")
        self.horizontalLayout_3.addWidget(self.edtImagePath)
        self.btnBraws = QtWidgets.QPushButton(self.centralwidget)
        self.btnBraws.setObjectName("btnBraws")
        self.horizontalLayout_3.addWidget(self.btnBraws)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.listImages = QtWidgets.QListWidget(self.centralwidget)
        self.listImages.setObjectName("listImages")
        self.verticalLayout.addWidget(self.listImages)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.edtX = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtX.sizePolicy().hasHeightForWidth())
        self.edtX.setSizePolicy(sizePolicy)
        self.edtX.setStatusTip("")
        self.edtX.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.edtX.setObjectName("edtX")
        self.horizontalLayout_9.addWidget(self.edtX)
        self.edtY = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtY.sizePolicy().hasHeightForWidth())
        self.edtY.setSizePolicy(sizePolicy)
        self.edtY.setMinimumSize(QtCore.QSize(0, 0))
        self.edtY.setStatusTip("")
        self.edtY.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.edtY.setObjectName("edtY")
        self.horizontalLayout_9.addWidget(self.edtY)
        self.edtW = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtW.sizePolicy().hasHeightForWidth())
        self.edtW.setSizePolicy(sizePolicy)
        self.edtW.setStatusTip("")
        self.edtW.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.edtW.setObjectName("edtW")
        self.horizontalLayout_9.addWidget(self.edtW)
        self.edtH = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtH.sizePolicy().hasHeightForWidth())
        self.edtH.setSizePolicy(sizePolicy)
        self.edtH.setStatusTip("")
        self.edtH.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.edtH.setText("")
        self.edtH.setObjectName("edtH")
        self.horizontalLayout_9.addWidget(self.edtH)
        self.btnMarkRect = QtWidgets.QPushButton(self.centralwidget)
        self.btnMarkRect.setObjectName("btnMarkRect")
        self.horizontalLayout_9.addWidget(self.btnMarkRect)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lblTotalImageNum = QtWidgets.QLabel(self.centralwidget)
        self.lblTotalImageNum.setObjectName("lblTotalImageNum")
        self.horizontalLayout_7.addWidget(self.lblTotalImageNum)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lblParsedImageNumber = QtWidgets.QLabel(self.centralwidget)
        self.lblParsedImageNumber.setObjectName("lblParsedImageNumber")
        self.horizontalLayout_2.addWidget(self.lblParsedImageNumber)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnStartTask = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartTask.setObjectName("btnStartTask")
        self.horizontalLayout.addWidget(self.btnStartTask)
        self.btnStopTask = QtWidgets.QPushButton(self.centralwidget)
        self.btnStopTask.setObjectName("btnStopTask")
        self.horizontalLayout.addWidget(self.btnStopTask)
        self.btnDumpResult = QtWidgets.QPushButton(self.centralwidget)
        self.btnDumpResult.setObjectName("btnDumpResult")
        self.horizontalLayout.addWidget(self.btnDumpResult)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(4, 20)
        self.verticalLayout.setStretch(6, 1)
        self.verticalLayout.setStretch(7, 1)
        self.verticalLayout.setStretch(8, 1)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setContentsMargins(8, 0, 8, 0)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gvPreview = QtWidgets.QGraphicsView(self.centralwidget)
        self.gvPreview.setObjectName("gvPreview")
        self.verticalLayout_2.addWidget(self.gvPreview)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbxPerson = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxPerson.setAutoFillBackground(False)
        self.cbxPerson.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.cbxPerson.setObjectName("cbxPerson")
        self.horizontalLayout_4.addWidget(self.cbxPerson)
        self.cbxBody = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxBody.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.cbxBody.setObjectName("cbxBody")
        self.horizontalLayout_4.addWidget(self.cbxBody)
        self.cbxFace = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxFace.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.cbxFace.setObjectName("cbxFace")
        self.horizontalLayout_4.addWidget(self.cbxFace)
        self.cbxBike = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxBike.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.cbxBike.setObjectName("cbxBike")
        self.horizontalLayout_4.addWidget(self.cbxBike)
        self.cbxCar = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxCar.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.cbxCar.setObjectName("cbxCar")
        self.horizontalLayout_4.addWidget(self.cbxCar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mtxtResponse = QtWidgets.QTextBrowser(self.centralwidget)
        self.mtxtResponse.setObjectName("mtxtResponse")
        self.horizontalLayout_5.addWidget(self.mtxtResponse)
        self.mtxtParseResult = QtWidgets.QTextBrowser(self.centralwidget)
        self.mtxtParseResult.setObjectName("mtxtParseResult")
        self.horizontalLayout_5.addWidget(self.mtxtParseResult)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout_2.setStretch(2, 3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        IOESDemo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(IOESDemo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1424, 23))
        self.menubar.setObjectName("menubar")
        IOESDemo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(IOESDemo)
        self.statusbar.setObjectName("statusbar")
        IOESDemo.setStatusBar(self.statusbar)

        self.retranslateUi(IOESDemo)
        QtCore.QMetaObject.connectSlotsByName(IOESDemo)

    def retranslateUi(self, IOESDemo):
        _translate = QtCore.QCoreApplication.translate
        IOESDemo.setWindowTitle(_translate("IOESDemo", "IOESDemo"))
        self.label.setText(_translate("IOESDemo", "算法服务URL地址"))
        self.edtURL.setText(_translate("IOESDemo", "http://192.168.1.222:9098/images/recog"))
        self.label_2.setText(_translate("IOESDemo", "本地图片路径"))
        self.btnBraws.setText(_translate("IOESDemo", "浏览"))
        self.btnMarkRect.setText(_translate("IOESDemo", "标注"))
        self.label_6.setText(_translate("IOESDemo", "图片总数："))
        self.lblTotalImageNum.setText(_translate("IOESDemo", "0"))
        self.label_3.setText(_translate("IOESDemo", "已识别数："))
        self.lblParsedImageNumber.setText(_translate("IOESDemo", "0"))
        self.btnStartTask.setText(_translate("IOESDemo", "提交任务"))
        self.btnStopTask.setText(_translate("IOESDemo", "终止任务"))
        self.btnDumpResult.setText(_translate("IOESDemo", "导出结果"))
        self.cbxPerson.setText(_translate("IOESDemo", "行人"))
        self.cbxBody.setText(_translate("IOESDemo", "身体"))
        self.cbxFace.setText(_translate("IOESDemo", "人脸"))
        self.cbxBike.setText(_translate("IOESDemo", "非机动车"))
        self.cbxCar.setText(_translate("IOESDemo", "机动车"))
