# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IOESDemo.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IOESDemo(object):
    def setupUi(self, IOESDemo):
        IOESDemo.setObjectName("IOESDemo")
        IOESDemo.resize(1424, 942)
        self.centralwidget = QtWidgets.QWidget(IOESDemo)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_6.setContentsMargins(8, -1, 8, -1)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.combxSericeType = QtWidgets.QComboBox(self.centralwidget)
        self.combxSericeType.setObjectName("combxSericeType")
        self.horizontalLayout_8.addWidget(self.combxSericeType)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.edtURL = QtWidgets.QLineEdit(self.centralwidget)
        self.edtURL.setObjectName("edtURL")
        self.verticalLayout.addWidget(self.edtURL)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edtImagePath = QtWidgets.QLineEdit(self.centralwidget)
        self.edtImagePath.setText("")
        self.edtImagePath.setReadOnly(True)
        self.edtImagePath.setObjectName("edtImagePath")
        self.horizontalLayout_3.addWidget(self.edtImagePath)
        self.btnBraws = QtWidgets.QPushButton(self.centralwidget)
        self.btnBraws.setObjectName("btnBraws")
        self.horizontalLayout_3.addWidget(self.btnBraws)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.combxModel = QtWidgets.QComboBox(self.centralwidget)
        self.combxModel.setObjectName("combxModel")
        self.horizontalLayout_10.addWidget(self.combxModel)
        self.horizontalLayout_10.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.combxBunchSize = QtWidgets.QComboBox(self.centralwidget)
        self.combxBunchSize.setObjectName("combxBunchSize")
        self.horizontalLayout_11.addWidget(self.combxBunchSize)
        self.horizontalLayout_11.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.listImages = QtWidgets.QListWidget(self.centralwidget)
        self.listImages.setObjectName("listImages")
        self.verticalLayout.addWidget(self.listImages)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.edtX = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtX.sizePolicy().hasHeightForWidth())
        self.edtX.setSizePolicy(sizePolicy)
        self.edtX.setStatusTip("")
        self.edtX.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.edtX.setObjectName("edtX")
        self.horizontalLayout_9.addWidget(self.edtX)
        self.btnMarkRect = QtWidgets.QPushButton(self.centralwidget)
        self.btnMarkRect.setObjectName("btnMarkRect")
        self.horizontalLayout_9.addWidget(self.btnMarkRect)
        self.horizontalLayout_9.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lblTotalImageNum = QtWidgets.QLabel(self.centralwidget)
        self.lblTotalImageNum.setObjectName("lblTotalImageNum")
        self.horizontalLayout_7.addWidget(self.lblTotalImageNum)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.lblParsedImageNumber = QtWidgets.QLabel(self.centralwidget)
        self.lblParsedImageNumber.setObjectName("lblParsedImageNumber")
        self.horizontalLayout_7.addWidget(self.lblParsedImageNumber)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lblTimeCost = QtWidgets.QLabel(self.centralwidget)
        self.lblTimeCost.setObjectName("lblTimeCost")
        self.horizontalLayout_2.addWidget(self.lblTimeCost)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnStartTask = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartTask.setObjectName("btnStartTask")
        self.horizontalLayout.addWidget(self.btnStartTask)
        self.btnStopTask = QtWidgets.QPushButton(self.centralwidget)
        self.btnStopTask.setObjectName("btnStopTask")
        self.horizontalLayout.addWidget(self.btnStopTask)
        self.btnDumpResult = QtWidgets.QPushButton(self.centralwidget)
        self.btnDumpResult.setObjectName("btnDumpResult")
        self.horizontalLayout.addWidget(self.btnDumpResult)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(5, 20)
        self.verticalLayout.setStretch(7, 1)
        self.verticalLayout.setStretch(8, 1)
        self.verticalLayout.setStretch(9, 1)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setContentsMargins(8, 0, 8, 0)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gvPreview = QtWidgets.QGraphicsView(self.centralwidget)
        self.gvPreview.setObjectName("gvPreview")
        self.verticalLayout_2.addWidget(self.gvPreview)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbxPerson = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxPerson.setAutoFillBackground(False)
        self.cbxPerson.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.cbxPerson.setChecked(True)
        self.cbxPerson.setObjectName("cbxPerson")
        self.horizontalLayout_4.addWidget(self.cbxPerson)
        self.cbxFace = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxFace.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.cbxFace.setChecked(True)
        self.cbxFace.setObjectName("cbxFace")
        self.horizontalLayout_4.addWidget(self.cbxFace)
        self.cbxHead = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxHead.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.cbxHead.setChecked(True)
        self.cbxHead.setObjectName("cbxHead")
        self.horizontalLayout_4.addWidget(self.cbxHead)
        self.cbxBody = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxBody.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.cbxBody.setChecked(True)
        self.cbxBody.setObjectName("cbxBody")
        self.horizontalLayout_4.addWidget(self.cbxBody)
        self.cbxCar = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxCar.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.cbxCar.setChecked(True)
        self.cbxCar.setObjectName("cbxCar")
        self.horizontalLayout_4.addWidget(self.cbxCar)
        self.cbxBike = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxBike.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.cbxBike.setChecked(True)
        self.cbxBike.setObjectName("cbxBike")
        self.horizontalLayout_4.addWidget(self.cbxBike)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mtxtResponse = QtWidgets.QTextBrowser(self.centralwidget)
        self.mtxtResponse.setObjectName("mtxtResponse")
        self.horizontalLayout_5.addWidget(self.mtxtResponse)
        self.mtxtParseResult = QtWidgets.QTextBrowser(self.centralwidget)
        self.mtxtParseResult.setObjectName("mtxtParseResult")
        self.horizontalLayout_5.addWidget(self.mtxtParseResult)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout_2.setStretch(2, 3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        IOESDemo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(IOESDemo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1424, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        IOESDemo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(IOESDemo)
        self.statusbar.setObjectName("statusbar")
        IOESDemo.setStatusBar(self.statusbar)
        self.menuCfgFull = QtWidgets.QAction(IOESDemo)
        self.menuCfgFull.setCheckable(True)
        self.menuCfgFull.setChecked(True)
        self.menuCfgFull.setObjectName("menuCfgFull")
        self.menuCfgPBC = QtWidgets.QAction(IOESDemo)
        self.menuCfgPBC.setCheckable(True)
        self.menuCfgPBC.setObjectName("menuCfgPBC")
        self.menuCfgFace = QtWidgets.QAction(IOESDemo)
        self.menuCfgFace.setCheckable(True)
        self.menuCfgFace.setObjectName("menuCfgFace")
        self.menuCfgPB = QtWidgets.QAction(IOESDemo)
        self.menuCfgPB.setObjectName("menuCfgPB")
        self.menuCfgCar = QtWidgets.QAction(IOESDemo)
        self.menuCfgCar.setObjectName("menuCfgCar")
        self.menuCfgBunch1 = QtWidgets.QAction(IOESDemo)
        self.menuCfgBunch1.setCheckable(True)
        self.menuCfgBunch1.setObjectName("menuCfgBunch1")
        self.menuCfgBunch5 = QtWidgets.QAction(IOESDemo)
        self.menuCfgBunch5.setCheckable(True)
        self.menuCfgBunch5.setObjectName("menuCfgBunch5")
        self.menuCfgBunch10 = QtWidgets.QAction(IOESDemo)
        self.menuCfgBunch10.setCheckable(True)
        self.menuCfgBunch10.setChecked(True)
        self.menuCfgBunch10.setObjectName("menuCfgBunch10")
        self.menuCfgThread1 = QtWidgets.QAction(IOESDemo)
        self.menuCfgThread1.setCheckable(True)
        self.menuCfgThread1.setChecked(True)
        self.menuCfgThread1.setObjectName("menuCfgThread1")
        self.menuCfgThread4 = QtWidgets.QAction(IOESDemo)
        self.menuCfgThread4.setCheckable(True)
        self.menuCfgThread4.setObjectName("menuCfgThread4")
        self.menuCfgThread8 = QtWidgets.QAction(IOESDemo)
        self.menuCfgThread8.setCheckable(True)
        self.menuCfgThread8.setObjectName("menuCfgThread8")
        self.menuCfgThread12 = QtWidgets.QAction(IOESDemo)
        self.menuCfgThread12.setCheckable(True)
        self.menuCfgThread12.setObjectName("menuCfgThread12")
        self.menuConfigDumpPicture = QtWidgets.QAction(IOESDemo)
        self.menuConfigDumpPicture.setCheckable(True)
        self.menuConfigDumpPicture.setObjectName("menuConfigDumpPicture")
        self.menuConfigSelfCheck = QtWidgets.QAction(IOESDemo)
        self.menuConfigSelfCheck.setCheckable(True)
        self.menuConfigSelfCheck.setObjectName("menuConfigSelfCheck")
        self.menu.addAction(self.menuConfigDumpPicture)
        self.menu.addAction(self.menuConfigSelfCheck)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(IOESDemo)
        self.combxSericeType.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(IOESDemo)

    def retranslateUi(self, IOESDemo):
        _translate = QtCore.QCoreApplication.translate
        IOESDemo.setWindowTitle(_translate("IOESDemo", "IOESDemo"))
        self.label.setText(_translate("IOESDemo", "服务URL"))
        self.edtURL.setText(_translate("IOESDemo", "http://192.168.1.222:9098/images/recog"))
        self.btnBraws.setText(_translate("IOESDemo", "选择图片目录"))
        self.label_2.setText(_translate("IOESDemo", "请求模式："))
        self.label_5.setText(_translate("IOESDemo", "单组图片："))
        self.edtX.setText(_translate("IOESDemo", "10, 10, 100, 100"))
        self.btnMarkRect.setText(_translate("IOESDemo", "标注"))
        self.label_6.setText(_translate("IOESDemo", "图片总数："))
        self.lblTotalImageNum.setText(_translate("IOESDemo", "0"))
        self.label_3.setText(_translate("IOESDemo", "已识别数:"))
        self.lblParsedImageNumber.setText(_translate("IOESDemo", "0"))
        self.label_4.setText(_translate("IOESDemo", "耗时(ms)："))
        self.lblTimeCost.setText(_translate("IOESDemo", "0"))
        self.btnStartTask.setText(_translate("IOESDemo", "提交任务"))
        self.btnStopTask.setText(_translate("IOESDemo", "终止任务"))
        self.btnDumpResult.setText(_translate("IOESDemo", "导出结果"))
        self.cbxPerson.setText(_translate("IOESDemo", "行人"))
        self.cbxFace.setText(_translate("IOESDemo", "人脸"))
        self.cbxHead.setText(_translate("IOESDemo", "头部"))
        self.cbxBody.setText(_translate("IOESDemo", "身体"))
        self.cbxCar.setText(_translate("IOESDemo", "机动车"))
        self.cbxBike.setText(_translate("IOESDemo", "非机动车"))
        self.menu.setTitle(_translate("IOESDemo", "配置"))
        self.menuCfgFull.setText(_translate("IOESDemo", "Full"))
        self.menuCfgPBC.setText(_translate("IOESDemo", "Person+Bike+Car"))
        self.menuCfgFace.setText(_translate("IOESDemo", "Face"))
        self.menuCfgPB.setText(_translate("IOESDemo", "Person+Bike"))
        self.menuCfgCar.setText(_translate("IOESDemo", "Car"))
        self.menuCfgBunch1.setText(_translate("IOESDemo", "1"))
        self.menuCfgBunch5.setText(_translate("IOESDemo", "5"))
        self.menuCfgBunch10.setText(_translate("IOESDemo", "10"))
        self.menuCfgThread1.setText(_translate("IOESDemo", "1"))
        self.menuCfgThread4.setText(_translate("IOESDemo", "4"))
        self.menuCfgThread8.setText(_translate("IOESDemo", "8"))
        self.menuCfgThread12.setText(_translate("IOESDemo", "12"))
        self.menuConfigDumpPicture.setText(_translate("IOESDemo", "DumpWithPicture"))
        self.menuConfigSelfCheck.setText(_translate("IOESDemo", "SelfCheck"))
